package om37;

//import junit.framework.Test;//Commented because of conflicting imports. I believe this could be for junit version 3. Was generated by maven
import junit.framework.TestCase;
import org.mockito.Mockito.*;
import junit.framework.TestSuite;

//Added by me
import org.junit.Test;
import org.junit.*;

import junit.*;

/**
 * Unit test for simple App.
 */
public class AppTest 
{
	
	App appUnderTest;
    public AppTest()
    {
    	
    }

    @Before
    public void setup()
    {
    	appUnderTest = new App();
    }
    
    /**
     * 
     * Rigourous Test :-)
     */
    @Test
    public void testApp()
    {
    	appUnderTest = new App();
        Assert.assertTrue( true );
    }
    
    @Test
    public void dummyMethod()
    {
    	Assert.assertEquals(1, appUnderTest.ret(1));
    }
}
